--ó·ëË1
--SELECT * From product WHERE cost >= 20000;
--ó·ëË2
--SELECT cust_id, cust_name FROM customer WHERE fax IS NULL;
--ó·ëË3
--SELECT sales_no, psales_no, prod_id, price FROM sales WHERE psales_no BETWEEN 110 AND 119 ORDER BY price DESC; 
--ó·ëË4
--SELECT prod_id, prod_name, cost * discount AS äÑà¯âøäi FROM product
--WHERE prod_id IN (102, 104, 106) ORDER BY äÑà¯âøäi DESC;
--ó·ëË5
--SELECT cust_id, cust_address, delivery_date FROM packedsales 
--WHERE cust_address LIKE '%èaíJãÊ%' AND (delivery_date BETWEEN '1996-01-01' AND '1996-12-31');
--ó·ëË6
--SELECT cust_id,cust_name, tel FROM customer 
--WHERE NOT (tel LIKE '03%' OR tel LIKE '06%');
--WHERE tel NOT LIKE '03%' AND tel NOT LIKE '06%';

